### PR TITLE
SDK constraint update. Fix #30.

### LINKED ISSUE #30: pubspec says sdk 1.8.0 is good enough but package_config requires 1.11
Running `pub get` on HEAD today (317635c120ba3d6a003e6041c0772eaf4a15a022) results in:
```shell
analyzer_cli > pub get
Resolving dependencies... (1.2s) 
Package package_config requires SDK version >=1.11.0-dev.0.0 <2.0.0 but the current SDK is 1.10.1.
```
Was it intensional to introduce a dependency on 1.11.x pre-release? The `pubspec.yaml` constraint is:
```yaml
  environment:
   sdk: '>=1.8.0 <2.0.0'
```
Either that needs to be updated or the version of `package_config` retrograded (or fixed to not require 1.11x).

### PR DESCRIPTION
**Pull request by pq**

### CODE REVIEW

**Comment by pq** [comment]
@bwilkerson PTAL.

For context, see #30.

cc: @chalin

**Comment by bwilkerson** [comment]
This adds a second constraint on a pre-release version of the SDK (rather than removing it). It would be better to change `package_config` to depend on a released version, if possible.

**Comment by pq** [comment]
@bwilkerson : I hear you.  Unfortunately, until 1.11 is released I think this may be as good as we can get.  I don't think retrograding `package_config` is an option. 

Paging @seaneagan since he was similarly resistant! :)

**Comment by bwilkerson** [comment]
> I don't think retrograding `package_config` is an option.

Ok. But we don't need to, and shouldn't, change the analyzer_cli constraints in order to force pub to choose a later version. If we're now dependent on an unpublished version of the SDK, then that's unfortunate. When we do release the SDK that `package_config` depends on users will automatically get the right version without us having to make a change.

I think that all that's required here is a post to #30 indicating the nature of the problem in `package_config` (and an invitation to raise the issue in that project).

**Comment by pq** [comment]
> If we're now dependent on an unpublished version of the SDK, then that's unfortunate. 

Maybe.  But I don't see how it makes a difference from a practical perspective.  `analyzer_cli`, like the entire analysis stack is pretty coupled to the SDK (and isn't meant to be consumed outside of the SDK besides).  For all practical purposes we could just as well set the constraint to `HEAD` (not that I'm suggesting it let alone now how one would).

But this is actually kind of academic really.  In the end, I think there are other reasons not to manually propagate version constraints.  I felt like this was not a bad time to do it but consider me convinced otherwise! :)

**Pull request closed without merging**
