### PR TITLE
Turn on the new task model by default in command-line analyzer.

### PR DESCRIPTION
**Pull request by stereotype441**
An option is added, "--disable-new-task-model", to allow the task model
to be disabled if necessary.

Note that at the moment, strong mode doesn't work with the new task
model.  So when strong mode is enabled, the option is ignored and the
new task model is unconditionally disabled.

### CODE REVIEW

**Comment by stereotype441** [comment]
@pq

**Comment by pq** [comment]
LGTM.

As discussed, we'll need to:
- back out my added `--enable-task-model` flag and
- fix lints (https://github.com/dart-lang/analyzer_cli/issues/64)
  before we can merge with `master` 

but I'm all for updated `DEPS` to point to this in the interim!

**Comment by pq** [comment]
FWIW:

> back out my added --enable-task-model flag 

https://codereview.chromium.org/1389113002/

**Comment by pq** [comment]
> back out my added --enable-task-model flag and

Done in https://github.com/dart-lang/analyzer_cli/commit/7dcdbb30e735582f0f3b9806085343a47256a279.

> fix lints (#64) before we can merge with master

Fixed w/ https://github.com/dart-lang/sdk/commit/fe76c6f3c4684122c70288d936e90def2eff6040.

From my perspective, we should be good to go.

**Pull request merged**
