### PR TITLE
add build: off to the windows build

### PR DESCRIPTION
**Pull request by devoncarew**
add build: off to the windows build (test a fix to the appveyor build)

### CODE REVIEW

**Comment by devoncarew** [comment]
@sethladd 

It looks like `build: off` is necessary; it tells appveyor that there is not a build step. This is used for things like python projects.

The build still fails (after all the tests run successfully). I suspect that the `pub run test` process is not exiting after the tests complete and appveyor eventually times out. Not sure why this is.

**Comment by devoncarew** [comment]
We could try an explicit `dart test/all.dart` instead of pub run. Also, removing the need to the `-j1` flag for `test` would give us a few more options. @stereotype441 re: not changing the cwd during test execution.

**Comment by devoncarew** [comment]
Switched over to using `dart test\all.dart` instead of `pub run test -j1` in order to work around the hang on test finish.

**Comment by stereotype441** [comment]
Hmm, switching to `dart test\all.dart` is unfortunate.  My concern is that this puts us in a situation where the Travis build automatically discovers all the tests, but the Appveyor build only runs the tests that we remember to explicitly list in test/all.dart.  Which means that there's a risk that when we add a new test file in the future, we'll forget to make the corresponding change to test/all.dart.

However, I can't really think of an alternative, so lgtm.

**Comment by devoncarew** [comment]
I agree there's now the possibility that someone will create a new file and not know remember to add it to test/all.dart. Hopefully something that @pq would catch in review.

We can also move travis over to test/all.dart as well in order to remove the disparity between testing the two platforms.

**Comment by pq** [comment]
Right.  I think for now that's up to a reviewer to catch.  A few things come to mind:
- maybe we should consider a build script that verifies `all.dart` is complete? Alternatively
- we could generate `all.dart` as a build step?

**Pull request merged**
